"""create product selection tables

Revision ID: db9b471259e3
Revises: 
Create Date: 2026-07-11 11:18:45.115165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9b471259e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selection_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cost_price_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('weight_g', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('length_cm', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('width_cm', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('declared_value_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selection_products_category'), 'selection_products', ['category'], unique=False)
    op.create_index(op.f('ix_selection_products_sku'), 'selection_products', ['sku'], unique=True)
    op.create_table('selection_market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('average_selling_price_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('competitor_count', sa.Integer(), nullable=False),
    sa.Column('demand_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('trend_factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['selection_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selection_market_data_product_id'), 'selection_market_data', ['product_id'], unique=False)
    op.create_table('selection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('market_data_id', sa.Integer(), nullable=False),
    sa.Column('estimated_retail_price_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_net_profit_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_roi', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('estimated_margin', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('estimated_tax_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_platform_fee_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_shipping_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_gross_profit_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('profit_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('demand_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('competition_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('logistics_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('recommendation_level', sa.String(length=16), nullable=False),
    sa.Column('recommendation_reasons', sa.JSON(), nullable=False),
    sa.Column('risk_warnings', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_data_id'], ['selection_market_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['selection_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selection_results_evaluated_at'), 'selection_results', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_selection_results_market_data_id'), 'selection_results', ['market_data_id'], unique=False)
    op.create_index(op.f('ix_selection_results_product_id'), 'selection_results', ['product_id'], unique=False)
    op.create_index(op.f('ix_selection_results_recommendation_level'), 'selection_results', ['recommendation_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selection_results_recommendation_level'), table_name='selection_results')
    op.drop_index(op.f('ix_selection_results_product_id'), table_name='selection_results')
    op.drop_index(op.f('ix_selection_results_market_data_id'), table_name='selection_results')
    op.drop_index(op.f('ix_selection_results_evaluated_at'), table_name='selection_results')
    op.drop_table('selection_results')
    op.drop_index(op.f('ix_selection_market_data_product_id'), table_name='selection_market_data')
    op.drop_table('selection_market_data')
    op.drop_index(op.f('ix_selection_products_sku'), table_name='selection_products')
    op.drop_index(op.f('ix_selection_products_category'), table_name='selection_products')
    op.drop_table('selection_products')
    # ### end Alembic commands ###
